'use client'

import { useEffect, useMemo, useState } from 'react'
import { Download, Pause, Play, SkipBack, SkipForward } from 'lucide-react'
import { useAnalyticsRun } from '@/hooks/use-analytics-run'
import type { Signal } from '@/lib/surveillance'
import { availableMetrics, displayLocationName, latestByLocation, metricLabels } from '@/lib/surveillance'
import { OperationsHeader } from './operations-header'
import { OperationsKpis } from './operations-kpis'
import { SurveillanceMap } from './surveillance-map'
import { PriorityAlertFeed } from './priority-alert-feed'
import { LocationRanking } from './location-ranking'
import { RiskTrendChart, SurveillanceChart } from './surveillance-chart'

function Shell({ children, run, loading }: {children:React.ReactNode;run:any;loading:boolean}) { return <main className="min-h-screen bg-[#080a0d] font-mono text-slate-300"><OperationsHeader run={run}/><div className="mx-auto max-w-7xl p-4 md:p-6">{loading ? <div className="border border-slate-800 bg-[#0d1015] p-6 text-sm text-slate-500">Loading surveillance artefact…</div> : !run ? <div className="border border-slate-800 bg-[#0d1015] p-6 text-sm text-slate-500">No generated model run is available.</div> : children}</div></main> }

function selectedSignals(signals: Signal[], locationId?: string) { return locationId ? signals.filter(signal=>signal.observation.location_id===locationId) : signals }
export function OperationsDashboard({ section = 'overview' }: { section?: string }) {
  const {run,loading}=useAnalyticsRun(); const [selectedId,setSelectedId]=useState<string>(); const [metric,setMetric]=useState('tests_completed')
  const activeId = selectedId ?? (run ? latestByLocation(run.signals).sort((a,b)=>b.risk_score-a.risk_score)[0]?.observation.location_id : undefined)
  const selected = run ? selectedSignals(run.signals,activeId) : []
  if (!run) return <Shell run={run} loading={loading}><></></Shell>
  const select=(signal:Signal)=>setSelectedId(signal.observation.location_id)
  let content:React.ReactNode
  if(section==='overview') content=<Overview run={run} selected={selected} selectedId={activeId} select={select} metric={metric} setMetric={setMetric}/>
  else if(section==='alerts') content=<Alerts run={run}/>
  else if(section==='surveillance') content=<Surveillance run={run} selected={selected} selectedId={activeId} select={select} metric={metric} setMetric={setMetric}/>
  else if(section==='locations') content=<Locations run={run} selectedId={activeId} select={select}/>
  else if(section==='replay') content=<Replay run={run} selectedId={activeId} select={select}/>
  else if(section==='evaluation') content=<Evaluation />
  else if(section==='data') content=<Data run={run}/>
  else if(section==='methods') content=<Methods />
  else content=<Research run={run}/>
  return <Shell run={run} loading={loading}>{content}</Shell>
}

function PageTitle({title, children}:{title:string;children?:React.ReactNode}) { return <div className="mb-5 border-b border-slate-800 pb-3"><h1 className="text-lg tracking-wide text-slate-100">{title}</h1>{children && <p className="mt-1 text-xs text-slate-500">{children}</p>}</div> }
function Overview({run,selected,selectedId,select,metric,setMetric}:any) { return <><PageTitle title="Surveillance operations overview">Current signals are generated from the selected model run.</PageTitle><OperationsKpis run={run}/><div className="mt-5 grid gap-5 lg:grid-cols-[1.65fr_.85fr]"><SurveillanceMap signals={run.signals} selectedId={selectedId} onSelect={select}/><PriorityAlertFeed alerts={run.alerts} limit={7}/></div><div className="mt-5 grid gap-5 lg:grid-cols-2"><SurveillanceChart signals={selected} metric={metric} onMetric={setMetric}/><RiskTrendChart signals={selected}/></div><div className="mt-5"><PriorityAlertFeed alerts={run.alerts}/></div></> }
function Alerts({run}:any) { return <><PageTitle title="Alert review">Each alert includes its model-derived driver, score, and persistence.</PageTitle><PriorityAlertFeed alerts={run.alerts}/></> }
function Surveillance({run,selected,selectedId,select,metric,setMetric}:any) { const locations=latestByLocation(run.signals); return <><PageTitle title="Surveillance explorer">Select a location and metric; visualisation is primary, rows are supporting evidence.</PageTitle><div className="mb-4 flex flex-wrap gap-2"><select value={selectedId ?? ''} onChange={e=>select(locations.find(l=>l.observation.location_id===e.target.value) ?? locations[0])} className="border border-slate-700 bg-[#0d1015] px-3 py-2 text-xs text-slate-200"><option value="">All locations</option>{locations.map(location=><option key={location.observation.location_id} value={location.observation.location_id}>{displayLocationName(location.observation.location_name)}</option>)}</select>{availableMetrics(selected).map(key=><button key={key} onClick={()=>setMetric(key)} className={`border px-3 py-2 text-xs ${metric===key?'border-cyan-700 text-cyan-200':'border-slate-800 text-slate-500'}`}>{metricLabels[key]}</button>)}</div><div className="grid gap-5 lg:grid-cols-[1.4fr_.6fr]"><SurveillanceChart signals={selected} metric={metric} onMetric={setMetric}/><RiskTrendChart signals={selected}/></div><div className="mt-5 overflow-x-auto border border-slate-800 bg-[#0d1015]"><table className="w-full text-left text-xs"><thead className="text-[10px] uppercase text-slate-500"><tr><th className="p-3">Date</th><th>Location</th><th>{metricLabels[metric]}</th><th>Risk</th><th>Baseline</th></tr></thead><tbody>{selected.slice().reverse().slice(0,80).map((signal:Signal)=><tr key={signal.observation.source_record_id} className="border-t border-slate-800"><td className="p-3">{signal.observation.observation_date}</td><td>{displayLocationName(signal.observation.location_name)}</td><td>{signal.observation[metric] ?? '—'}</td><td className="text-amber-300">{signal.risk_score.toFixed(2)}</td><td className="text-slate-500">{signal.drivers.find(driver=>driver.metric===metric)?.expected ?? '—'}</td></tr>)}</tbody></table></div></> }
function Locations({run,selectedId,select}:any) { return <><PageTitle title="Location surveillance">Select a marker or ranked location to inspect its current signal.</PageTitle><div className="grid gap-5 lg:grid-cols-[1.3fr_.7fr]"><SurveillanceMap signals={run.signals} selectedId={selectedId} onSelect={select}/><LocationRanking signals={run.signals} onSelect={select}/></div></> }
function Replay({run,selectedId,select}:any) { const dates=useMemo<string[]>(()=>[...new Set<string>(run.signals.map((s:Signal)=>String(s.observation.observation_date)))].sort(),[run]); const [index,setIndex]=useState(dates.length-1); const [playing,setPlaying]=useState(false); useEffect(()=>{if(!playing)return; const timer=setInterval(()=>setIndex(current=>current>=dates.length-1?0:current+1),900);return()=>clearInterval(timer)},[playing,dates.length]); const date=dates[index]; const view=run.signals.filter((s:Signal)=>s.observation.observation_date<=date); return <><PageTitle title="Retrospective replay">Move through the precomputed model run without exposing future observations.</PageTitle><div className="border border-slate-800 bg-[#0d1015] p-4"><div className="flex flex-wrap items-center gap-3"><span className="text-sm text-slate-100">REPLAY · {date}</span><button onClick={()=>setIndex(Math.max(0,index-1))} className="border border-slate-700 p-2"><SkipBack size={14}/></button><button onClick={()=>setPlaying(!playing)} className="border border-cyan-800 bg-cyan-950/30 p-2 text-cyan-200">{playing?<Pause size={14}/>:<Play size={14}/>}</button><button onClick={()=>setIndex(Math.min(dates.length-1,index+1))} className="border border-slate-700 p-2"><SkipForward size={14}/></button><input aria-label="Replay date" className="min-w-[200px] flex-1 accent-cyan-500" type="range" min="0" max={dates.length-1} value={index} onChange={e=>setIndex(Number(e.target.value))}/></div></div><div className="mt-5 grid gap-5 lg:grid-cols-[1.5fr_.5fr]"><SurveillanceMap signals={view} selectedId={selectedId} onSelect={select}/><PriorityAlertFeed alerts={run.alerts.filter((a:any)=>a.start_date<=date)} limit={7}/></div><div className="mt-5"><RiskTrendChart signals={view}/></div></> }
function Evaluation() { const [data,setData]=useState<any>(); useEffect(()=>{fetch('/analytics/evaluation.json').then(r=>r.ok?r.json():null).then(setData)},[]); const cards=data?[['Event detection rate',data.event_detection_rate==null?'—':`${Math.round(data.event_detection_rate*100)}%`],['Detected events',data.detected_events],['Generated alerts',data.generated_alerts],['Detection delay',data.detection_delay_days==null?'—':`${data.detection_delay_days} days`]]:[]; return <><PageTitle title="Benchmark evaluation">Metrics apply to the current labelled benchmark run.</PageTitle>{data?<><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{cards.map(([label,value])=><div key={String(label)} className="border border-slate-800 bg-[#0d1015] p-4"><p className="text-[10px] uppercase text-slate-500">{label}</p><p className="mt-2 text-2xl text-slate-100">{value}</p></div>)}</div><a href="/analytics/evaluation.json" download className="mt-5 inline-flex items-center gap-2 border border-slate-700 px-3 py-2 text-xs text-slate-300"><Download size={14}/> Download evaluation JSON</a></>:<p className="text-sm text-slate-500">Loading evaluation artefact…</p>}</> }
function Data({run}:any) { return <><PageTitle title="Data and provenance">Source details and limitations are preserved with the analytical artefact.</PageTitle><div className="grid gap-4 md:grid-cols-2"><Panel title="Current model run" body={`Run ${run.run_id}; ${run.records_scored} observations scored; ${run.model_version}; configuration ${run.configuration_version}.`}/><Panel title="Provenance" body="Canonical observations retain source, dataset, record identity, import time, and data-quality flags. See the local data inventory for source coverage and limitations."/></div></> }
function Methods() { return <><PageTitle title="Methods and limitations">ProDrome produces surveillance signals for verification, not autonomous outbreak declarations.</PageTitle><div className="grid gap-4 md:grid-cols-2"><Panel title="Baseline and change" body="Chronological robust baselines, positive change detection, persistence, and transparent weights are used before alerting."/><Panel title="Multivariate and spatial support" body="Isolation Forest runs only when usable historical features exist. Multi-location activity can corroborate, but never independently declares, a signal."/></div></> }
function Research({run}:any) { return <><PageTitle title="Research console">Technical run and artefact details.</PageTitle><pre className="overflow-auto border border-slate-800 bg-[#0d1015] p-4 text-xs text-slate-400">{JSON.stringify({run_id:run.run_id,model_version:run.model_version,configuration_version:run.configuration_version,created_at:run.created_at,records_scored:run.records_scored},null,2)}</pre></> }
function Panel({title,body}:{title:string;body:string}) { return <div className="border border-slate-800 bg-[#0d1015] p-4"><h2 className="text-sm text-slate-100">{title}</h2><p className="mt-2 text-xs leading-6 text-slate-400">{body}</p></div> }
