'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'

type Run = { run_id: string; model_version: string; configuration_version: string; created_at: string; records_scored: number; alerts: any[]; signals: any[] }
const routes = [
  ['/', 'Overview'], ['/alerts', 'Alerts'], ['/surveillance', 'Surveillance'], ['/locations', 'Locations'],
  ['/replay', 'Replay'], ['/evaluation', 'Evaluation'], ['/data', 'Data & provenance'], ['/methods', 'Methods'], ['/research', 'Research'],
]

function label(value: string) { return value.replaceAll('_', ' ') }
function alertText(alert: any) {
  const driver = alert.primary_driver
  if (!driver?.metric) return 'Elevated surveillance signal'
  return `${label(driver.metric)} ${driver.observed ?? 'signal'}; expected baseline ${driver.expected ?? 'not available'}`
}

export default function ProDromeConsole({ section = 'overview' }: { section?: string }) {
  const [run, setRun] = useState<Run | null>(null)
  useEffect(() => { fetch('/analytics/latest-run.json').then(r => r.ok ? r.json() : null).then(setRun).catch(() => setRun(null)) }, [])
  const alerts = run?.alerts ?? []
  const mode = alerts[0]?.mode ?? 'SYNTHETIC'
  const locations = useMemo(() => new Set((run?.signals ?? []).map(s => s.observation.location_id)).size, [run])
  const latest = useMemo(() => (run?.signals ?? []).slice(-12).reverse(), [run])
  const title = routes.find(([, name]) => name.toLowerCase().startsWith(section === 'data' ? 'data' : section))?.[1] ?? 'Overview'
  return <main className="min-h-screen bg-[#080a0d] text-slate-300 font-mono">
    <header className="border-b border-slate-800 bg-[#0b0d11] px-4 py-3 sticky top-0 z-20">
      <div className="flex flex-wrap items-center gap-x-5 gap-y-2">
        <Link href="/" className="font-semibold text-slate-100 tracking-[.16em] text-sm">PRODROME</Link>
        <span className="border border-amber-600/60 bg-amber-950/30 px-2 py-1 text-[10px] tracking-wider text-amber-300">DATA MODE · {mode}</span>
        <span className="text-[10px] text-slate-500">{mode === 'SYNTHETIC' ? 'SIMULATED, LABELLED TEST HARNESS' : 'RETROSPECTIVE ANALYSIS'}</span>
        <span className="ml-auto text-[10px] text-slate-500">MODEL {run?.model_version ?? 'artefact loading…'} · {run?.run_id ?? 'no generated run'}</span>
      </div>
      <nav className="mt-3 flex gap-1 overflow-x-auto text-[11px]">{routes.map(([href, name]) => <Link key={href} href={href} className="whitespace-nowrap px-2 py-1 text-slate-500 hover:bg-slate-800 hover:text-slate-100">{name}</Link>)}</nav>
    </header>
    <section className="mx-auto max-w-7xl p-4 md:p-6">
      <div className="mb-5 flex items-baseline justify-between border-b border-slate-800 pb-3"><div><h1 className="text-lg tracking-wide text-slate-100">{title}</h1><p className="mt-1 text-xs text-slate-500">Digital early-warning surveillance research console. Signals require human verification.</p></div><span className="text-[10px] text-slate-600">{run?.created_at ? `RUN ${new Date(run.created_at).toISOString()}` : 'Generate an artefact with python -m analytics'}</span></div>
      {!run ? <div className="border border-slate-800 bg-slate-900/30 p-5 text-sm text-slate-400">No generated model artefact is available. Run <code>python -m analytics generate-synthetic</code>, then <code>python -m analytics replay</code>.</div> : section === 'methods' ? <Methods /> : section === 'data' ? <Data run={run} /> : section === 'research' ? <Research run={run} /> : section === 'evaluation' ? <Evaluation /> : section === 'replay' ? <Replay run={run} /> : section === 'locations' ? <Locations signals={run.signals} /> : section === 'surveillance' ? <Surveillance signals={run.signals} /> : <Overview run={run} alerts={alerts} locations={locations} latest={latest} section={section} />}
    </section>
  </main>
}

function Overview({ run, alerts, locations, latest, section }: {run:Run; alerts:any[];locations:number;latest:any[];section:string}) {
  const shown = section === 'alerts' ? alerts : alerts.slice(0, 8)
  return <><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[['records scored',run.records_scored],['locations represented',locations],['generated signals',alerts.length],['high severity',alerts.filter(a=>a.severity==='high').length]].map(([key,value])=><div key={String(key)} className="border border-slate-800 bg-[#0d1015] p-3"><p className="text-[10px] uppercase tracking-wider text-slate-500">{key}</p><p className="mt-2 text-2xl text-slate-100">{value}</p></div>)}</div>
  <div className="mt-5 grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><div className="border border-slate-800 bg-[#0d1015]"><div className="border-b border-slate-800 px-3 py-2 text-xs text-slate-400">Generated surveillance alerts · retrospective/model-generated</div>{shown.length ? shown.map(a=><article key={a.alert_id} className="border-b border-slate-800/80 p-3 last:border-0"><div className="flex items-center gap-2"><span className="border border-amber-700/60 px-1.5 py-.5 text-[10px] uppercase text-amber-300">{a.severity}</span><span className="text-sm text-slate-100">{a.location}</span><span className="text-xs text-slate-500">{a.pathogen}</span><span className="ml-auto text-xs text-slate-400">risk {a.risk_score}</span></div><p className="mt-2 text-xs leading-5 text-slate-400">Elevated surveillance signal: {alertText(a)}. Persistence: {a.persistence} reporting periods. {a.verification_action}</p></article>) : <p className="p-4 text-sm text-slate-500">No alert crosses the configured threshold in this model run.</p>}</div>
  <div className="border border-slate-800 bg-[#0d1015]"><div className="border-b border-slate-800 px-3 py-2 text-xs text-slate-400">Latest scored observations</div>{latest.map(s=><div key={s.observation.source_record_id} className="flex justify-between border-b border-slate-800/70 px-3 py-2 text-[11px]"><span>{s.observation.location_name}</span><span className="text-slate-500">{s.observation.observation_date}</span><span className="text-amber-300">{s.risk_score}</span></div>)}</div></div></>
}
function Surveillance({ signals }: {signals:any[]}) { return <div className="border border-slate-800 bg-[#0d1015] overflow-auto"><table className="w-full text-left text-xs"><thead className="text-slate-500"><tr><th className="p-3">Date</th><th>Location</th><th>Tests</th><th>Positives</th><th>Positivity</th><th>Risk</th><th>Drivers</th></tr></thead><tbody>{signals.slice(-80).reverse().map(s=><tr key={s.observation.source_record_id} className="border-t border-slate-800/70"><td className="p-3">{s.observation.observation_date}</td><td>{s.observation.location_name}</td><td>{s.observation.tests_completed ?? '—'}</td><td>{s.observation.positive_tests ?? '—'}</td><td>{s.observation.positivity_rate == null ? '—' : `${(s.observation.positivity_rate*100).toFixed(1)}%`}</td><td className="text-amber-300">{s.risk_score}</td><td className="text-slate-500">{s.drivers.map((d:any)=>label(d.metric)).join(', ') || '—'}</td></tr>)}</tbody></table></div> }
function Locations({ signals }: {signals:any[]}) { const locations:any[]=[]; const seen=new Set(); signals.forEach(s=>{const o=s.observation;if(!seen.has(o.location_id)){seen.add(o.location_id);locations.push(o)}}); return <div className="grid gap-3 md:grid-cols-2">{locations.map(o=><div key={o.location_id} className="border border-slate-800 bg-[#0d1015] p-4"><p className="text-slate-100">{o.location_name}</p><p className="mt-2 text-xs text-slate-500">{o.location_type} · {o.region || o.country}</p><p className="mt-2 text-[11px] text-amber-300">{o.location_type === 'synthetic_facility' ? 'SIMULATED FACILITY — NOT A PRODUCTION CONNECTION' : 'No geographic inference beyond source metadata'}</p></div>)}</div> }
function Replay({run}:{run:Run}) { return <div className="border border-slate-800 bg-[#0d1015] p-5"><p className="text-sm text-slate-200">RETROSPECTIVE REPLAY</p><p className="mt-3 text-xs leading-6 text-slate-400">This artefact was calculated chronologically. At each period, only previous and current observations were available to baseline and anomaly models. Use the CLI with <code>--as-of YYYY-MM-DD</code> to inspect a replay checkpoint.</p><pre className="mt-4 overflow-auto border border-slate-800 bg-black/20 p-3 text-[11px] text-slate-400">python -m analytics replay --dataset synthetic-lab-network --as-of 2025-01-06</pre></div> }
function Evaluation(){ const [evaluation,setEvaluation]=useState<any>(null); useEffect(()=>{fetch('/analytics/evaluation.json').then(r=>r.ok?r.json():null).then(setEvaluation).catch(()=>null)},[]); return <div className="border border-slate-800 bg-[#0d1015] p-5"><p className="text-sm text-slate-200">SYNTHETIC BENCHMARK</p>{evaluation ? <pre className="mt-3 overflow-auto text-xs text-slate-400">{JSON.stringify(evaluation,null,2)}</pre> : <p className="mt-3 text-xs text-slate-500">Run <code>python -m analytics evaluate</code> to publish evaluation results. Results apply only to simulated labelled scenarios.</p>}</div> }
function Data({run}:{run:Run}){return <div className="grid gap-3 md:grid-cols-2"><div className="border border-slate-800 bg-[#0d1015] p-4"><p className="text-slate-100">Model artefact</p><dl className="mt-3 space-y-2 text-xs text-slate-400"><div>Model version: {run.model_version}</div><div>Configuration: {run.configuration_version}</div><div>Records: {run.records_scored}</div><div>Created: {run.created_at}</div></dl></div><div className="border border-slate-800 bg-[#0d1015] p-4"><p className="text-slate-100">Provenance boundary</p><p className="mt-3 text-xs leading-6 text-slate-400">Every canonical row retains source ID, dataset ID, source record ID, import time, and quality flags. Source descriptions and checksums are in the Data Inventory.</p><Link href="/docs/data-inventory.md" className="mt-3 inline-block text-xs text-blue-300">View source inventory →</Link></div></div>}
function Methods(){return <div className="grid gap-3 md:grid-cols-2">{[['Robust baseline','Rolling median and median absolute deviation; seasonal modelling is intentionally deferred until data history and cadence are sufficient.'],['Change detection','A transparent positive CUSUM-style contribution captures sustained departures.'],['Multivariate anomaly','Isolation Forest uses only populated, historical features and a fixed seed.'],['Human verification','A score is an elevated surveillance signal, never autonomous outbreak confirmation.']].map(([name,text])=><div key={name} className="border border-slate-800 bg-[#0d1015] p-4"><p className="text-sm text-slate-100">{name}</p><p className="mt-2 text-xs leading-6 text-slate-400">{text}</p></div>)}</div>}
function Research({run}:{run:Run}){return <div className="border border-slate-800 bg-[#0d1015] p-5 text-xs leading-6 text-slate-400"><p className="text-sm text-slate-100">Research console</p><p className="mt-3">Dataset/model metadata, runs and exports are local artefacts. At deployment protect this route with Cloudflare Access. No public signup or operator workflow is implemented.</p><pre className="mt-4 overflow-auto border border-slate-800 bg-black/20 p-3">{JSON.stringify({run_id:run.run_id, configuration:run.configuration_version, created_at:run.created_at, exported_files:['public/analytics/latest-run.json','public/analytics/evaluation.json']},null,2)}</pre></div>}
